### ISSUE TITLE
Can you add Mac OSX install instructions for pester?

### ISSUE THREAD

**Issue by djangofan** [pester/docs#168]
Can you add Mac OSX install instructions for pester?

Here is the basic outline of how to do it:

1.  brew install powershell
2.  pwsh
3.  Find-Module pester -Repository psgallery | Install-Module -MinimumVersion 4.3.1 -Force -SkipPublisherCheck -Scope CurrentUser
4.   Import-Module Pester -PassThru
5.   Invoke-Pester .\infrastructure_tests\buildValidation.Tests.ps1

**Comment by fflaten** [comment]
Thanks for the suggestion. 

I don't have access to a Mac, but `Install-Module -Name Pester` should suffice. Could you help me confirm?

If so, then it's covered in the [quick start](https://pester.dev/docs/quick-start#installing-pester).

PowerShell is a prereq. and out-of-scope I believe. No need for Pester if you don't already have PowerShell, right? 😄  

We could add Mac+Unix to https://pester.dev/docs/introduction/installation just to be clear though. That page mostly exists because Windows has had x methods and conflicts which require special steps. For Mac+Unix it should be a lot simpler.

**Comment by djangofan** [comment]
The answer , in retrospect is obvious, but it could help adoption of Pester, if Mac/Linux users find this information easy to locate.

**Comment by nohwnd** [comment]
Note to self: Also update windows versions on that installation page.
