### ISSUE TITLE
Disable Netlify PrettyUrls

### ISSUE THREAD

**Issue by bravo-kernel** [pester/docs#36]
@nohwnd, I (finally) figured out how to prevent Netlify from altering the docusaurus links (which is now causing causing 301 redirects and 404 problems).

See facebook/docusaurus#2394 (comment)

Changes settings take effect immediately, After changing, try by browsing directly to e.g. https://pester.dev/docs/commands/Add-AssertionOperator (the casing should not change to lower).

**Comment by nohwnd** [comment]
@bravo-kernel is there some action I need to take? Going to that link I see that the url is lowercase in the address bar. 

![image](https://user-images.githubusercontent.com/5735905/76733150-8be84d80-6760-11ea-9719-3500c882316b.png)

**Comment by nohwnd** [comment]
Ah found it. Is that just a weird naming on their side? Because the top checkbox says: Disable asset optimization, so unchecking it should go from doing noting at all, to doing all optimizations, minus url rewrite. 

![image](https://user-images.githubusercontent.com/5735905/76733933-10879b80-6762-11ea-9334-6684b66ef8db.png)

**Comment by nohwnd** [comment]
anyways, I disabled it and it works as you said :)

**Comment by bravo-kernel** [comment]
Good job, now let Google index correct casing :)
