### ISSUE TITLE
Quickstart and related documenation incorrectly show . "$here$sut" instead of . "$here\$sut"

### ISSUE THREAD

**Issue by dtrue** [pester/docs#38]
Looks like these are missing another \ escape character

. "$here$sut" instead of . "$here\$sut"

**Comment by bravo-kernel** [comment]
@dtrue Did you notice the `Edit this Page` buttons at the bottom of the pages?

Feel to propose fixes where neccessary.

**Comment by nohwnd** [comment]
@bravo-kernel I think this is code rendering issue rather than content issue. The MD contains `"$here\$sut"` correctly. Maybe there is some option that we need to disable?

**Comment by bravo-kernel** [comment]
@nohwnd you might be correct. I have asked for confirmation because the behavior is not consistent when testing against the lib used to generate the D2 code blocks.

See https://codesandbox.io/s/prism-react-renderer-example-o9gdb:

- select `basic.js`
- L12 and L13 both render incorrectly
- However, D2 does render L13 correctly

**Comment by bravo-kernel** [comment]
Created D2 ticket https://github.com/facebook/docusaurus/issues/2441

Root cause seems to be found in https://github.com/mdx-js/mdx/issues/902

**Comment by nohwnd** [comment]
When you said that the community around docusaurus will help us solve bugs you were not lying 🙂

**Comment by bravo-kernel** [comment]
;)
