### ISSUE TITLE
Documentation for Pester v5 does not exist

### ISSUE THREAD

**Issue by xtqqczze** [pester/docs#45]
Now Pester v5 is released, documentation is out of date for all commands:
https://github.com/pester/Pester/releases/tag/5.0.0

**Comment by OnAzureCloud9** [comment]
Yes, I noticed that some parameters in the `Invoke-Pester` cmdlet such as `-OutputFile` are missing and I don't see it listed in the breaking changes such as the change between `-Script` and `-Path`. The [documentation online](https://pester.dev/docs/commands/Invoke-Pester) still shows the `-OutputFile` as a valid parameter so I'm assuming it's outdated.

**Comment by xtqqczze** [comment]
According to the [release notes](https://github.com/pester/Pester/releases/tag/5.0.0), "documentation is out of date for all commands".

@OnAzureCloud9 If you check the release notes, you can find the answer to your question in the section: *Simple and advanced interface*.

**Comment by OnAzureCloud9** [comment]
@xtqqczze thanks for pointing out the "documentation is out of date for all commands" point as I did not see that. That makes sense since I tried the `Get-Help` cmdlet which provided almost no information. The _Simple and advanced interface_ section was useful (saw it as well after my post) but still seems to leave some things out such as how to specify the name of the output file. It seems that the only option is by enabling the `-CI` switch which outputs to a `testResults.xml` file. If you're running multiple test sets and want multiple files I'm afraid this will get overridden. On Pester 4 you can specify the output file name. For now I'm sticking with 4.10.1 until 5.1 gets released and documentation is updated.

**Comment by nohwnd** [comment]
I released version 5.0.1 that adds the missing parameters for backwards compatibility. https://github.com/pester/Pester/releases/tag/5.0.1

**Comment by bravo-kernel** [comment]
Closing as resolved
